openapi: 3.0.1
info:
  title: Server Setup API
  description: API for managing server setup including installation, configuration, and monitoring.
  version: 1.0.0

paths:
  /install/system-essentials/system-updates:
    post:
      summary: Install system updates
      description: |
        Endpoint to install system updates.
      operationId: installSystemUpdates
      requestBody:
        required: false
      responses:
        '200':
          description: System updates installed successfully
        '500':
          description: Internal server error

  /install/system-essentials/nginx:
    post:
      summary: Install Nginx
      description: |
        Endpoint to install and configure Nginx.
      operationId: installNginx
      requestBody:
        required: false
      responses:
        '200':
          description: Nginx installed and configured successfully
        '500':
          description: Internal server error

  /install/system-essentials/ssl-tools:
    post:
      summary: Install SSL tools
      description: |
        Endpoint to install SSL tools including Certbot.
      operationId: installSslTools
      requestBody:
        required: false
      responses:
        '200':
          description: SSL tools installed successfully
        '500':
          description: Internal server error

  /install/system-essentials/firewall:
    post:
      summary: Install firewall
      description: |
        Endpoint to install and configure UFW firewall.
      operationId: installFirewall
      requestBody:
        required: false
      responses:
        '200':
          description: Firewall installed and configured successfully
        '500':
          description: Internal server error

  /configure/nginx:
    post:
      summary: Configure Nginx
      description: |
        Endpoint to configure Nginx.
      operationId: configureNginx
      requestBody:
        required: false
      responses:
        '200':
          description: Nginx configured successfully
        '500':
          description: Internal server error

  /configure/ssl:
    post:
      summary: Configure SSL
      description: |
        Endpoint to configure SSL for domains using Certbot.
      operationId: configureSsl
      requestBody:
        required: false
      responses:
        '200':
          description: SSL configured successfully
        '500':
          description: Internal server error

  /configure/firewall:
    post:
      summary: Configure firewall
      description: |
        Endpoint to set up and enable UFW firewall rules.
      operationId: configureFirewall
      requestBody:
        required: false
      responses:
        '200':
          description: Firewall configured successfully
        '500':
          description: Internal server error

  /configure/virtual-host:
    post:
      summary: Configure virtual host
      description: |
        Endpoint to set up and test Nginx configurations for virtual hosts.
      operationId: configureVirtualHost
      requestBody:
        required: false
      responses:
        '200':
          description: Virtual host configured successfully
        '500':
          description: Internal server error

  /configure/systemd-for-vapor:
    post:
      summary: Configure systemd for Vapor
      description: |
        Endpoint to set up the Vapor application as a systemd service.
      operationId: configureSystemdForVapor
      requestBody:
        required: false
      responses:
        '200':
          description: Systemd configured successfully
        '500':
          description: Internal server error

  /configure/nginx-for-vapor:
    post:
      summary: Configure Nginx for Vapor
      description: |
        Endpoint to configure Nginx to proxy requests to the Vapor application.
      operationId: configureNginxForVapor
      requestBody:
        required: false
      responses:
        '200':
          description: Nginx configured for Vapor successfully
        '500':
          description: Internal server error

  /configure/monitor-nginx:
    post:
      summary: Monitor Nginx
      description: |
        Endpoint to check if Nginx is active and running.
      operationId: monitorNginx
      requestBody:
        required: false
      responses:
        '200':
          description: Nginx is running
        '500':
          description: Nginx is not running

  /configure/monitor-web-server:
    post:
      summary: Monitor web server
      description: |
        Endpoint to verify web server response and content.
      operationId: monitorWebServer
      requestBody:
        required: false
      responses:
        '200':
          description: Web server response verified
        '500':
          description: Web server response verification failed

  /configure/verify-ssl-certificate:
    post:
      summary: Verify SSL certificate
      description: |
        Endpoint to validate the SSL certificate's expiration and authenticity.
      operationId: verifySslCertificate
      requestBody:
        required: false
      responses:
        '200':
          description: SSL certificate verified
        '500':
          description: SSL certificate verification failed
