version: '3'

services:
  vapor:
    image: vapor/vapor:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_NAME: $DATABASE_NAME
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - vapor
