name: 'Manage Secrets'
description: 'Action to manage and validate secrets'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
    type: string
  vps_ssh_key:
    description: 'VPS SSH Key'
    required: true
    type: string
  vps_username:
    description: 'VPS Username'
    required: true
    type: string
  vps_ip:
    description: 'VPS IP Address'
    required: true
    type: string
  deploy_dir:
    description: 'Deployment Directory'
    required: true
    type: string
  repo_owner:
    description: 'Repository Owner'
    required: true
    type: string
  app_name:
    description: 'Application Name'
    required: true
    type: string
  domain:
    description: 'Production Domain'
    required: true
    type: string
  staging_domain:
    description: 'Staging Domain'
    required: true
    type: string
  db_name:
    description: 'Database Name'
    required: true
    type: string
  db_user:
    description: 'Database User'
    required: true
    type: string
  db_password:
    description: 'Database Password'
    required: true
    type: string
  email:
    description: 'Email'
    required: true
    type: string
  main_dir:
    description: 'Main Directory'
    required: true
    type: string
  nydus_port:
    description: 'Nydus Port'
    required: true
    type: string
  redisai_port:
    description: 'RedisAI Port'
    required: true
    type: string
  redis_port:
    description: 'Redis Port'
    required: true
    type: string
  repo_name:
    description: 'Repository Name'
    required: true
    type: string
  runner_token:
    description: 'Runner Token'
    required: true
    type: string
runs:
  using: 'node20'
  main: 'index.js'
