name: Linting

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Run Linters
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << 'EOF'
          docker pull ghcr.io/${{ secrets.REPO_OWNER }}/linting
          docker run --rm -v $(pwd):/linting ghcr.io/${{ secrets.REPO_OWNER }}/linting
EOF
