name: Linting

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.G_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: Pull linting Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/linting

      - name: List files in linting directory
        run: docker run --rm -v ${{ github.workspace }}:/linting ghcr.io/${{ github.repository_owner }}/linting ls /linting

      - name: Run linters
        run: docker run --rm -v ${{ github.workspace }}:/linting ghcr.io/${{ github.repository_owner }}/linting
