name: Main Workflow for Production

on:
  push:
    branches:
      - main
    paths:
      - '**'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call setup workflow
        uses: ./.github/workflows/setup.yml

  ufw-config:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call ufw-config workflow
        uses: ./.github/workflows/ufw-config.yml

  build:
    runs-on: ubuntu-latest
    needs: ufw-config
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call build workflow
        uses: ./.github/workflows/build.yml

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call test workflow
        uses: ./.github/workflows/test.yml

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call deploy-production workflow
        uses: ./.github/workflows/deploy-production.yml
