name: Main Workflow for Staging

on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  ufw-config:
    uses: ./.github/workflows/ufw-config.yml

  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  deploy:
    uses: ./.github/workflows/deploy-staging.yml
