name: Main Workflow for Production

on:
  push:
    branches:
      - main
    paths:
      - '**'
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    secrets: inherit

  ufw-config:
    needs: setup
    uses: ./.github/workflows/ufw-config.yml
    secrets: inherit

  build:
    needs: ufw-config
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy:
    needs: test
    uses: ./.github/workflows/deploy-production.yml
    secrets: inherit
