name: Main Workflow for Production

on:
  push:
    branches:
      - production
    paths:
      - '**'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup job
        run: echo "Setup job step"

  ufw-config:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: UFW Configuration
        run: echo "UFW Configuration step"

  build:
    runs-on: ubuntu-latest
    needs: ufw-config
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: echo "Build step"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: echo "Test step"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploy step"
