name: Main Workflow for Production

on:
  push:
    branches:
      - production
    paths:
      - '**'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup VPS
        uses: ./.github/workflows/setup.yml

  ufw-config:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: UFW Configuration
        uses: ./.github/workflows/ufw-config.yml

  build:
    runs-on: ubuntu-latest
    needs: ufw-config
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: ./.github/workflows/build.yml

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/workflows/test.yml

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        uses: ./.github/workflows/deploy-production.yml
