name: Setup VPS

on: [workflow_call]

jobs:
  setup-vps:
    runs-on: self-hosted

    steps:
      # Debugging step to check if secret is accessible
      - name: Check SSH key length
        run: echo "SSH key length: ${#secrets.VPS_SSH_KEY}"

      # Set up SSH agent to allow connecting to the VPS
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # Install Docker and Dependencies on the VPS
      - name: Install Docker and Dependencies
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << 'EOF'
          sudo apt update
          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo apt install -y nginx certbot python3-certbot-nginx
          EOF
