name: Configure UFW

on: [workflow_call]

jobs:
  configure-ufw:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up SSH agent to allow connecting to the VPS
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # Configure UFW on the VPS
      - name: Configure UFW
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << 'EOF'
          sudo ufw allow 22/tcp   # Ensure SSH remains allowed
          sudo ufw allow 80/tcp   # Allow HTTP
          sudo ufw allow 443/tcp  # Allow HTTPS
          sudo ufw allow 5432/tcp # Allow PostgreSQL
          sudo ufw allow 6379/tcp # Allow Redis
          sudo ufw allow 6378/tcp # Allow RedisAI
          sudo ufw allow 8080/tcp # Allow Application (Production)
          sudo ufw allow 8081/tcp # Allow Application (Staging)
          sudo ufw allow 2224/tcp # Allow NYDUS Service
          sudo ufw default deny incoming  # Deny all other incoming connections
          sudo ufw enable
          EOF
