name: Verify Secrets

on: workflow_call

jobs:
  verify-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify GitHub Secrets
        run: |
          if [[ -z "${{ secrets.GITHUB_TOKEN }}" ]]; then echo "GITHUB_TOKEN is not set"; exit 1; fi
          if [[ -z "${{ secrets.VPS_SSH_KEY }}" ]]; then echo "VPS_SSH_KEY is not set"; exit 1; fi
          if [[ -z "${{ secrets.VPS_USERNAME }}" ]]; then echo "VPS_USERNAME is not set"; exit 1; fi
          if [[ -z "${{ secrets.VPS_IP }}" ]]; then echo "VPS_IP is not set"; exit 1; fi
          if [[ -z "${{ secrets.DEPLOY_DIR }}" ]]; then echo "DEPLOY_DIR is not set"; exit 1; fi
          if [[ -z "${{ secrets.REPO_OWNER }}" ]]; then echo "REPO_OWNER is not set"; exit 1; fi
          if [[ -z "${{ secrets.APP_NAME }}" ]]; then echo "APP_NAME is not set"; exit 1; fi
          if [[ -z "${{ secrets.DOMAIN }}" ]]; then echo "DOMAIN is not set"; exit 1; fi
          if [[ -z "${{ secrets.STAGING_DOMAIN }}" ]]; then echo "STAGING_DOMAIN is not set"; exit 1; fi
          if [[ -z "${{ secrets.G_TOKEN }}" ]]; then echo "G_TOKEN is not set"; exit 1; fi

