name: Verify Secrets

on: workflow_call

jobs:
  verify-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify GitHub Secrets
        run: |
          if [[ -z "${{ inputs.github_token }}" ]]; then echo "GITHUB_TOKEN is not set"; exit 1; fi
          if [[ -z "${{ inputs.vps_ssh_key }}" ]]; then echo "VPS_SSH_KEY is not set"; exit 1; fi
          if [[ -z "${{ inputs.vps_username }}" ]]; then echo "VPS_USERNAME is not set"; exit 1; fi
          if [[ -z "${{ inputs.vps_ip }}" ]]; then echo "VPS_IP is not set"; exit 1; fi
          if [[ -z "${{ inputs.deploy_dir }}" ]]; then echo "DEPLOY_DIR is not set"; exit 1; fi
          if [[ -z "${{ inputs.repo_owner }}" ]]; then echo "REPO_OWNER is not set"; exit 1; fi
          if [[ -z "${{ inputs.app_name }}" ]]; then echo "APP_NAME is not set"; exit 1; fi
          if [[ -z "${{ inputs.domain }}" ]]; then echo "DOMAIN is not set"; exit 1; fi
          if [[ -z "${{ inputs.staging_domain }}" ]]; then echo "STAGING_DOMAIN is not set"; exit 1; fi
          if [[ -z "${{ inputs.g_token }}" ]]; then echo "G_TOKEN is not set"; exit 1; fi

inputs:
  github_token:
    description: "GitHub Token"
    required: true
  vps_ssh_key:
    description: "VPS SSH Key"
    required: true
  vps_username:
    description: "VPS Username"
    required: true
  vps_ip:
    description: "VPS IP Address"
    required: true
  deploy_dir:
    description: "Deployment Directory"
    required: true
  repo_owner:
    description: "Repository Owner"
    required: true
  app_name:
    description: "Application Name"
    required: true
  domain:
    description: "Production Domain"
    required: true
  staging_domain:
    description: "Staging Domain"
    required: true
  g_token:
    description: "GitHub Token for Actions"
    required: true
