name: Verify Secrets

on: workflow_call

jobs:
  verify-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify GitHub Secrets
        run: |
          if [[ -z "${{ secrets.GITHUB_TOKEN }}" ]]; then echo "GITHUB_TOKEN is not set"; exit 1; fi
          if [[ -z "${{ inputs.VPS_SSH_KEY }}" ]]; then echo "VPS_SSH_KEY is not set"; exit 1; fi
          if [[ -z "${{ inputs.VPS_USERNAME }}" ]]; then echo "VPS_USERNAME is not set"; exit 1; fi
          if [[ -z "${{ inputs.VPS_IP }}" ]]; then echo "VPS_IP is not set"; exit 1; fi
          if [[ -z "${{ inputs.DEPLOY_DIR }}" ]]; then echo "DEPLOY_DIR is not set"; exit 1; fi
          if [[ -z "${{ inputs.REPO_OWNER }}" ]]; then echo "REPO_OWNER is not set"; exit 1; fi
          if [[ -z "${{ inputs.APP_NAME }}" ]]; then echo "APP_NAME is not set"; exit 1; fi
          if [[ -z "${{ inputs.DOMAIN }}" ]]; then echo "DOMAIN is not set"; exit 1; fi
          if [[ -z "${{ inputs.STAGING_DOMAIN }}" ]]; then echo "STAGING_DOMAIN is not set"; exit 1; fi
          if [[ -z "${{ inputs.G_TOKEN }}" ]]; then echo "G_TOKEN is not set"; exit 1; fi
